### ISSUE TITLE
add geographical distance between institutions

### ISSUE THREAD

**Issue by chrished** [f-hafner/mag_sample#12]
- [x] load institution list with coordinates -> count to check it's not too many, use cng institutions
- [x] calculate pairwise distances
- [x] write to sql db

**Comment by chrished** [comment]
I messed up a little and based the branch on the wrong branch. I just redid it and based it on main. 

Distance calculation takes a moment but less then 15 minutes.  

I just wait for being allowed to write to sql db @f-hafner

**Comment by chrished** [comment]
geopy should be added to the sciencecareer environment and distances_cng.py to the pipeline

**Comment by f-hafner** [comment]
Just added it to pipeline. Also renamed indexes in this table and cng_institutions to be more consistent. 
- I will add the geopy dependency in a separate issue
- Can you run the whole pipeline in `clean_link_institutions.sh` to update the indexes and make sure everything works? because the script is executed not from the root directory, but from `src/dataprep/`, you should also remove the `src.dataprep.` part

**Comment by chrished** [comment]
done, pipeline ran through after small adjustment in script as you suggested
